# Generated by Django 4.2.14 on 2024-09-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('trigger_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Triggers',
        ),
    ]
