# Generated by Django 4.2.14 on 2024-09-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_trigger_delete_triggers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='text',
        ),
        migrations.AddField(
            model_name='trigger',
            name='message_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
